# Default application configuration that all configurations inherit from.

scss_files: "src/scss/**/*.scss"
plugin_directories: ['.scss-linters']

# List of gem names to load custom linters from (make sure they are already
# installed)
plugin_gems: []

# Default severity of all linters.
severity: warning

linters:
  ChainedClasses:
    enabled: true

  Comment:
    enabled: false

  DuplicateProperty:
    enabled: true
    ignore_consecutive: true

  HexLength:
    enabled: true
    style: long

  HexNotation:
    enabled: true
    style: uppercase

  Indentation:
    enabled: false

  PropertySortOrder:
    enabled: false

  StringQuotes:
    enabled: true
    style: double_quotes

  Compass::*:
    enabled: false